### ISSUE TITLE
/index.html returns 404

### ISSUE THREAD

**Issue by katoquro** [sysgears/grain-theme-template#4]
It works well for these cases

```
/index           -> /
/index.html      -> /
/index.md        -> /
```

described here http://sysgears.com/grain/docs/latest/#resource-mapping

but in returns 404 on /index.html in preview mode

**Comment by vlasenko** [comment]
This is the problem in Grain core. We should make Grain preview work the same as Apache HTTP Server with Index pages.

Gene, please take a look

**Comment by evgenijolshanskij** [comment]
I have already fixed this issue, so that it behaves exactly the same way as Apache HTTP Server.

**Comment by vlasenko** [comment]
Fixed with commit:
https://github.com/sysgears/grain/commit/9fe153f6635cec9be7cf18c6f2e52c57c03ccdb8
